version: "3.9"

services:
  api:
    build: .
    container_name: quickwrite_api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    # Para produção, NÃO monte volumes (para não sobrescrever dist)
    # volumes:
    #   - .:/app
    restart: always

  db:
    image: postgres:16-alpine
    container_name: quickwrite_db
    environment:
      POSTGRES_DB: quickwrite
      POSTGRES_USER: quickwrite_user
      POSTGRES_PASSWORD: quickwrite_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
